### ISSUE TITLE
Latest SDK version errors at Prod

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4769]
**Describe the bug**

https://cdn.discordapp.com/attachments/1032671441084235828/1136156488029720646/Screenshot_2023-08-02_at_10.09.55_AM.png

https://discord.com/channels/454734546869551114/1136138873378975754/1136145830634602536

We need to test out the prod hosting of bridge.connext.network and do load testing with wrapper version to make sure this doesn't pop up on prod again.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by prathmeshkhandelwal1** [comment]
Tried overloading the API for different routes worked fr me, wasn’t able to repro the issue, rechecked by @just-a-node as well.

**Comment by just-a-node** [comment]
Results from a much larger load test have revealed issues in infra scaling:

```
errors.ETIMEDOUT: .............................................................. 5218
http.codes.200: ................................................................ 7371
http.codes.502: ................................................................ 15987
http.downloaded_bytes: ......................................................... 4291933
http.request_rate: ............................................................. 45/sec
http.requests: ................................................................. 28576
http.response_time:
  min: ......................................................................... 36
  max: ......................................................................... 9925
  median: ...................................................................... 53
  p95: ......................................................................... 1525.7
  p99: ......................................................................... 6439.7
http.responses: ................................................................ 23358
plugins.metrics-by-endpoint./approveIfNeeded.codes.502: ........................ 3782
plugins.metrics-by-endpoint./calculateAmountReceived.codes.200: ................ 2648
plugins.metrics-by-endpoint./calculateAmountReceived.codes.502: ................ 4434
plugins.metrics-by-endpoint./estimateRelayerFee.codes.200: ..................... 2429
plugins.metrics-by-endpoint./estimateRelayerFee.codes.502: ..................... 3957
plugins.metrics-by-endpoint./xcall.codes.200: .................................. 2294
plugins.metrics-by-endpoint./xcall.codes.502: .................................. 3814
plugins.metrics-by-endpoint.response_time./approveIfNeeded:
  min: ......................................................................... 42
  max: ......................................................................... 9766
  median: ...................................................................... 50.9
  p95: ......................................................................... 58.6
  p99: ......................................................................... 127.8
plugins.metrics-by-endpoint.response_time./calculateAmountReceived:
  min: ......................................................................... 47
  max: ......................................................................... 9816
  median: ...................................................................... 55.2
  p95: ......................................................................... 3395.5
  p99: ......................................................................... 7865.6
plugins.metrics-by-endpoint.response_time./estimateRelayerFee:
  min: ......................................................................... 36
  max: ......................................................................... 9859
  median: ...................................................................... 53
  p95: ......................................................................... 1556.5
  p99: ......................................................................... 6702.6
plugins.metrics-by-endpoint.response_time./xcall:
  min: ......................................................................... 46
  max: ......................................................................... 9925
  median: ...................................................................... 51.9
  p95: ......................................................................... 889.1
  p99: ......................................................................... 4867
```
